{
 "title": "Sensors Data Visualisation",
 "description": "Shows the time series value of Temperature, Humidity, Vox, Nox, Sound, Vibrations, CO2 level, and Particulate matter.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Sensor_Module",
    "query": "SELECT DISTINCT Topic FROM Master.sensors"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "This panel display the value of temperature",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT Temperature, Date FROM Master.sensors "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "This panel display the value of humidity.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT Humidity, Date FROM Master.sensors "
    }
   ]
  },
  {
   "title": "Carbon dioxide",
   "type": "timeseries",
   "description": "This panel display the concentration of CO2 in air",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT CO2, Date FROM Master.sensors "
    }
   ]
  },
  {
   "title": "SPS30",
   "type": "timeseries",
   "description": "This panel display the mass concentration range of Particulate Matter",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT SPS30, Date FROM Master.sensors"
    }
   ]
  },
  {
   "title": "NOx",
   "type": "timeseries",
   "description": "Display the value of Nitrogen oxide pollutants in air",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT NoxIndex, Date FROM Master.sensors "
    }
   ]
  },
  {
   "title": "VOx",
   "type": "timeseries",
   "description": "The panel displays the Volatile organic matter in the air",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT VocIndex, Date FROM Master.sensors"
    }
   ]
  },
  {
   "title": "Sound Intensity",
   "type": "timeseries",
   "description": "This panel displays sound intensity at the analog signal level and measures the ADC unit range from 0 to 1023 depending on the outside sound level.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ADC" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT Sound, Date FROM Master.sensors"
    }
   ]
  },
  {
   "title": "Vibration Intensity",
   "type": "timeseries",
   "description": "This panel display the vibrational intensity in the surrounding environment. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "dataset": "Master",
     "rawSql": "SELECT Vibration, Date FROM Master.sensors"
    }
   ]
  }
 ]
}